# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{boilerplate}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Geraud Boyer"]
  s.date = %q{2010-09-24}
  s.description = %q{Basic code for a rails app}
  s.email = %q{geraud@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/controllers/boilerplate/facebook_sessions_controller.rb",
     "app/controllers/boilerplate/user_sessions_controller.rb",
     "app/helpers/javascript_helper.rb",
     "app/javascripts/boilerplate/application.js",
     "app/javascripts/boilerplate/util/actions.js",
     "app/javascripts/boilerplate/util/facebook.js",
     "app/javascripts/boilerplate/util/twitter.js",
     "app/models/boilerplate/user.rb",
     "boilerplate.gemspec",
     "config/routes.rb",
     "lib/boilerplate.rb",
     "lib/boilerplate/authentication.rb",
     "lib/boilerplate/config.rb",
     "lib/boilerplate/engine.rb",
     "lib/boilerplate/facebook.rb",
     "lib/boilerplate/feedback_handling.rb",
     "lib/boilerplate/pagination.rb",
     "lib/generators/boilerplate/migration/migration_generator.rb",
     "lib/generators/boilerplate/migration/templates/migration.rb",
     "lib/generators/boilerplate/update_js/update_js_generator.rb",
     "lib/tasks/boilerplate.rake",
     "spec/boilerplate_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/geraud/boilerplate}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Basic code for a rails app}
  s.test_files = [
    "spec/boilerplate_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<authlogic>, [">= 0"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<rest-graph>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<authlogic>, [">= 0"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<rest-graph>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<authlogic>, [">= 0"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<rest-graph>, [">= 0"])
  end
end

